server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      # CORS 설정
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://10.0.2.15:3000"
              - "https://*.ngrok-free.dev"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      
      # 라우팅 설정
      routes:
        # User Service
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /api/$\{segment}
        
        # Community Service
        - id: community-service
          uri: ${COMMUNITY_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/community/**
        
        # Recommendation Service
        - id: recommendation-service
          uri: ${RECOMMENDATION_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/recommendation/**
        
        # Place Service
        - id: place-service
          uri: ${PLACE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/places/**

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# 로깅 설정
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO

