server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  # Jackson Configuration (JSON 직렬화 시간대 설정)
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd'T'HH:mm:ss
  
  cloud:
    gateway:
      # CORS 설정
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:3000"
              - "http://10.0.2.15:3000"
              - "https://*.ngrok-free.dev"
              - "https://*.ngrok-free.app"
              - "https://*.ngrok.io"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      
      # 라우팅 설정
      routes:
        # User Service
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<segment>.*), /api/$\{segment}
        
        # Community Service
        - id: community-service
          uri: ${COMMUNITY_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/community/**
        
        # Recommendation Service
        - id: recommendation-service
          uri: ${RECOMMENDATION_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/recommendation/**
        
        # Place Service - Places
        - id: place-service-places
          uri: ${PLACE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/places/**
        
        # Place Service - Categories
        - id: place-service-categories
          uri: ${PLACE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/categories/**
        
        # Place Service - Reviews
        - id: place-service-reviews
          uri: ${PLACE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/reviews/**
        
        # Place Service - Static Files (Uploads)
        - id: place-service-uploads
          uri: ${PLACE_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/uploads/**

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus,metrics
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# 로깅 설정
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO

