version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user-service-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_service
      MYSQL_USER: user_service
      MYSQL_PASSWORD: user_service_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./01_create_database.sql:/docker-entrypoint-initdb.d/01_create_database.sql
      - ./04_docker_setup.sql:/docker-entrypoint-initdb.d/04_docker_setup.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - user-service-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: user-service-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - user-service-network

volumes:
  mysql_data:
    driver: local

networks:
  user-service-network:
    driver: bridge
