server:
  port: ${SERVER_PORT:8084}
  servlet:
    context-path: /api

spring:
  application:
    name: recommendation-service
  
  # Jackson Configuration (JSON 직렬화 시간대 설정)
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd'T'HH:mm:ss
  
  # Database Configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:recommendation_db}
    username: ${DB_USERNAME:maltan_user}
    password: ${DB_PASSWORD:maltan1234}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Redis 설정 제거 (캐싱 불필요)
  # redis:
  #   host: ${REDIS_HOST:localhost}
  #   port: ${REDIS_PORT:6379}
  #   timeout: 2000ms

# Place Service 설정
place:
  service:
    url: ${PLACE_SERVICE_URL:http://localhost:8082}

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# 로깅 설정
logging:
  level:
    com.maltan.recommendation: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

