version: '3.8'

services:
  user-service:
    build:
      context: ../backend/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
      - DB_HOST=172.17.0.1
      - DB_PORT=3306
      - DB_NAME=userdb
      - DB_USERNAME=root
      - DB_PASSWORD=1234
    networks:
      - maltan-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/user/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  place-service:
    build:
      context: ../backend/place-service
      dockerfile: Dockerfile
    container_name: place-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
      - DB_HOST=172.17.0.1
      - DB_PORT=3306
      - DB_NAME=placedb
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - UPLOAD_DIR=/app/uploads
    networks:
      - maltan-network
    restart: unless-stopped
    volumes:
      - place_uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  maltan-network:
    driver: bridge

volumes:
  place_uploads: