name: Build and Test Community Service

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn clean package -DskipTests
      
      - name: Run tests
        run: mvn test
      
      - name: Build Docker image
        run: docker build -t community-service:test .
      
      - name: Test Docker image
        run: |
          docker run -d --name test-service -p 8083:8083 \
            -e DB_HOST=localhost \
            -e DB_NAME=test_db \
            community-service:test
          sleep 10
          docker logs test-service
          docker stop test-service
          docker rm test-service

