server:
  port: 8085

spring:
  application:
    name: monitoring-service
  
  # Jackson Configuration
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd'T'HH:mm:ss

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# 로깅 설정
logging:
  level:
    root: INFO
    com.maltan.monitoring: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

