spring:
  application:
    name: place-service
  
  # Updated: 2025-10-26 - Security configuration for development mode
  # Jackson Configuration (JSON 직렬화 시간대 설정)
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd'T'HH:mm:ss
  
  # MySQL 데이터베이스 연결 설정 (환경 변수 사용)
  datasource:
    url: jdbc:mysql://${DB_HOST:10.0.2.15}:${DB_PORT:3306}/${DB_NAME:placedb}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&connectTimeout=10000&socketTimeout=10000
    username: ${DB_USERNAME:maltan_user}
    password: ${DB_PASSWORD:maltan1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      initialization-fail-timeout: 0  # 시작 시 실패해도 계속 재시도
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true  # 데이터소스 초기화 지연
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
  
  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB
      enabled: true
  
  # Security 설정
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# 서버 설정
server:
  port: ${SERVER_PORT:8082}

# 로깅 설정
logging:
  level:
    com.example.placeservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/place-service.log

# 애플리케이션 설정
app:
  upload:
    dir: ${UPLOAD_DIR:uploads}
    max-file-size: ${MAX_FILE_SIZE:5242880} # 5MB (10MB에서 줄임)
    allowed-types: image/jpeg,image/jpg,image/png,image/gif,image/webp
    max-photos-per-place: 10 # 장소당 최대 사진 개수
    enable-compression: true # 이미지 압축 활성화
    image:
      max-width: 1920 # 이미지 최대 너비
      max-height: 1080 # 이미지 최대 높이
      quality: 0.8 # 이미지 품질 (0.0 ~ 1.0)
    thumbnail:
      size: 300 # 썸네일 크기 (정사각형)
  
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:8080
      - https://*.ngrok-free.app
      - https://*.ngrok-free.dev
      - https://*.ngrok.io
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# 액추에이터 설정 (모니터링)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# 정보 설정
info:
  app:
    name: Place Service
    description: 장소 및 리뷰 관리 서비스
    version: 1.0.0
  java:
    version: ${java.version}
  spring:
    version: ${spring-boot.version}

---
# Docker 환경 설정
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:mysql://${DB_HOST:10.0.2.15}:${DB_PORT:3306}/placedb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:maltan_user}
    password: ${DB_PASSWORD:maltan1234}
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

app:
  upload:
    dir: /app/uploads
    max-file-size: 5242880 # 5MB
    allowed-types: image/jpeg,image/jpg,image/png,image/gif,image/webp
    max-photos-per-place: 10
    enable-compression: true
    image:
      max-width: 1920
      max-height: 1080
      quality: 0.8
    thumbnail:
      size: 300
  
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:8080
      - https://*.ngrok-free.app
      - https://*.ngrok-free.dev
      - https://*.ngrok.io
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

logging:
  level:
    root: INFO
    com.example.placeservice: INFO

---
# 프로덕션 환경 설정
spring:
  config:
    activate:
      on-profile: production
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

logging:
  level:
    root: WARN
    com.example.placeservice: INFO
  file:
    name: /var/log/place-service/application.log

app:
  upload:
    dir: /var/uploads/place-service