name: Deploy Monitoring Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/monitoring-service/**'
      - 'docker/docker-compose.yml'
      - '.github/workflows/deploy-monitoring.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build with Maven
        working-directory: ./backend/monitoring-service
        run: ./mvnw clean package -DskipTests
      
      - name: Deploy with Docker Compose
        run: |
          cd docker
          
          # monitoring-service 이미지 재빌드
          docker-compose build monitoring-service
          
          # monitoring-service만 재시작 (기존 서비스 영향 없음)
          docker-compose up -d --no-deps monitoring-service
          
          # gateway-service 재시작 (새 라우팅 적용)
          docker-compose restart gateway-service
          
          echo "Waiting for services to start..."
          sleep 10
          
          # 헬스 체크
          echo "=== Monitoring Service Status ==="
          docker-compose ps monitoring-service
          
          echo "=== Monitoring Service Logs ==="
          docker-compose logs --tail=50 monitoring-service
          
          echo "=== Gateway Service Logs ==="
          docker-compose logs --tail=20 gateway-service
          
          echo "✅ Monitoring Service deployed successfully!"

