name: Deploy Monitoring Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/monitoring-service/**'
      - 'docker/docker-compose.yml'
      - '.github/workflows/deploy-monitoring.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build with Maven
        working-directory: ./backend/monitoring-service
        run: mvn clean package -DskipTests
      
      - name: Deploy with Docker Compose
        run: |
          cd docker
          
          # 현재 실행 중인 서비스 확인
          echo "=== Current Running Services ==="
          docker-compose ps
          
          # 기존 컨테이너 완전히 제거 (ContainerConfig 에러 방지)
          echo "=== Stopping and Removing Old Container ==="
          docker-compose stop monitoring-service || true
          docker-compose rm -f monitoring-service || true
          
          # 기존 이미지 제거
          echo "=== Removing Old Image ==="
          docker rmi docker_monitoring-service || true
          
          # monitoring-service 이미지 재빌드
          echo "=== Building Monitoring Service ==="
          docker-compose build --no-cache monitoring-service
          
          # monitoring-service 시작 (기존 서비스 영향 없음)
          echo "=== Starting Monitoring Service ==="
          docker-compose up -d monitoring-service
          
          # gateway-service 재시작 (새 라우팅 적용) - 없으면 시작
          echo "=== Restarting Gateway Service ==="
          docker-compose up -d gateway-service || echo "Gateway service will be started instead"
          
          echo "Waiting for services to initialize..."
          sleep 10
          
          # 헬스 체크
          echo "=== All Services Status ==="
          docker-compose ps
          
          echo "=== Monitoring Service Logs ==="
          docker-compose logs --tail=50 monitoring-service
          
          echo "=== Gateway Service Status ==="
          docker ps | grep gateway-service || echo "Gateway service not running"
          
          if docker ps | grep -q gateway-service; then
            echo "=== Gateway Service Logs ==="
            docker-compose logs --tail=20 gateway-service
          fi
          
          # Monitoring Service API 테스트
          echo "=== Testing Monitoring Service API ==="
          sleep 5
          curl -f http://localhost:8085/api/monitoring/system/metrics || echo "Monitoring API not ready yet"
          
          echo "✅ Monitoring Service deployed successfully!"

