name: Deploy Gateway Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/gateway-service/**'
      - '.github/workflows/deploy-gateway.yml'

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      - name: Build with Maven
        run: |
          cd backend/gateway-service
          mvn clean package -DskipTests
      
      - name: Build Docker Image
        run: |
          cd backend/gateway-service
          docker build -t gateway-service:latest .
      
      - name: Stop and Remove Old Container
        run: |
          docker stop gateway-service || true
          docker rm gateway-service || true
      
      - name: Run New Container
        run: |
          docker run -d \
            --name gateway-service \
            --network maltan-network \
            --restart unless-stopped \
            -p 8080:8080 \
            -e USER_SERVICE_URL=http://10.0.2.15:8081 \
            -e COMMUNITY_SERVICE_URL=http://10.0.2.15:8083 \
            -e RECOMMENDATION_SERVICE_URL=http://10.0.2.15:8084 \
            -e PLACE_SERVICE_URL=http://10.0.2.15:8082 \
            gateway-service:latest
      
      - name: Check Container Status
        run: |
          sleep 10
          docker ps | grep gateway-service
          docker logs gateway-service --tail 50
