name: Deploy User Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/user-service/**'
      - '.github/workflows/deploy-user.yml'
  workflow_dispatch:  # 수동 실행 가능

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build User Service
        working-directory: backend/user-service
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test
      
      - name: Build Docker Image
        working-directory: backend/user-service
        run: |
          docker build -t user-service:latest .
      
      - name: Stop Old Container
        run: |
          docker stop user-service || true
          docker rm user-service || true
      
      - name: Run New Container
        run: |
          docker run -d \
            --name user-service \
            --network docker_maltan-network \
            --restart unless-stopped \
            -p 8081:8081 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e DB_HOST=10.0.2.15 \
            -e DB_PORT=3306 \
            -e DB_NAME=user_service \
            -e DB_USERNAME=root \
            -e DB_PASSWORD=1234 \
            -e SERVER_PORT=8081 \
            -e JWT_SECRET=your-secret-key-here-min-32-characters-long-for-security \
            -e JWT_EXPIRATION=86400000 \
            user-service:latest
      
      - name: Health Check
        run: |
          sleep 10
          docker ps | grep user-service
          docker logs --tail 50 user-service
